surge-synthesizer/sst-jucegui

.github/workflows/feature.yml
README.md

But explicitly do *not* make a binary available since we
don't associate this particular instance with either a licensed
JUCE or a GPL3 program

Setup Github Actions for PR Builds

---

cmake/CPM.cmake

Update get_cpm script to match upstream.
allowing the cpm-main-script download
to resume if it has previously failed
as in:
https://github.com/free-audio/clap-juce-extensions/pull/116

Let CPM recover from failed download

---

CMakeLists.txt

This should have been part of #13 but I forgot to add it there.

Don't download additional dependencies if you are a submodule

---

examples/scxt-wireframes/MainWindow.h
examples/scxt-wireframes/SCXTWireframesMain.cpp

There's now a reasonable imlpementation of the block layout from the SCXT Figma Wireframe. Now to make some widgets look right. Then to port it to the SCXT engine. So just two steps left and we're done.

Block Layout following ED's figma

---

examples/component-demo/ExampleUtils.h
include/sst/jucegui/components/ContinuousParamEditor.h
include/sst/jucegui/data/Continuous.h
src/sst/jucegui/components/ContinuousParamEditor.cpp

Added support stuff to be able to get the default value of source and use it in mouse double click handler for relevant components. The double click handling might need to be implemented in a more fancy way later as currently whatever the mouse down and mouse up handlers are doing, will also be executed multiple times.

Default value support 

---

include/sst/jucegui/components/NamedPanel.h
src/sst/jucegui/components/NamedPanel.cpp

enabled enables the hamburger. setName resets the named panel name.

Tweaks around enabled and name

---

include/sst/jucegui/components/ContinuousParamEditor.h
include/sst/jucegui/components/MultiSwitch.h
include/sst/jucegui/components/NamedPanel.h
include/sst/jucegui/components/ToggleButton.h
scripts/fix_file_comments.pl
src/sst/jucegui/components/ContinuousParamEditor.cpp
src/sst/jucegui/components/DraggableTextEditableValue.cpp
src/sst/jucegui/components/Knob.cpp
src/sst/jucegui/components/NamedPanel.cpp
src/sst/jucegui/components/ToggleButton.cpp
src/sst/jucegui/style/StyleAndSettingsComsumer.cpp
src/sst/jucegui/style/StyleSheet.cpp

- enabled = false -> no events for sliders etc...
- Named Panel gets an option to be togglable
- Draggable Text gets a reset-to-default on blank string
- Remove some specious debug logging
- clang-format everywhere
- ToggleButton adds FILLED and LABELED mode

Sunday QOL Items

---

include/sst/jucegui/components/NamedPanel.h
include/sst/jucegui/style/StyleAndSettingsConsumer.h
src/sst/jucegui/components/NamedPanel.cpp
src/sst/jucegui/style/StyleSheet.cpp

- Style Sheet fix and find way better. API change that style() can return null in early initialization path.
- Named Panel gets selected and centered label properties

Style Fixes; Named Pamel Improvements

---

include/sst/jucegui/components/GlyphPainter.h
include/sst/jucegui/components/ToggleButton.h
src/sst/jucegui/components/GlyphPainter.cpp
src/sst/jucegui/components/ToggleButton.cpp

ToggleButton basically gets a naked glyph mode
Metronome glyph suitable for temposync for now
API points to allow same

Add a metronome glyph; add Glyph mode to toggle button

---

examples/component-demo/CoupledControls.h
examples/component-demo/CustomStyleDemo.h
examples/component-demo/DraggableTextDemo.h
examples/component-demo/HSliderDemo.h
examples/component-demo/KnobDemo.h
examples/component-demo/MixerPrototype.h
examples/component-demo/VSliderDemo.h
include/sst/jucegui/component-adapters/DiscreteToReference.h
include/sst/jucegui/components/ComponentBase.h
include/sst/jucegui/components/DiscreteParamEditor.h
include/sst/jucegui/data/Continuous.h
include/sst/jucegui/data/Discrete.h
src/sst/jucegui/components/ContinuousParamEditor.cpp
src/sst/jucegui/components/DraggableTextEditableValue.cpp
src/sst/jucegui/components/HSlider.cpp
src/sst/jucegui/components/HSliderFilled.cpp
src/sst/jucegui/components/Knob.cpp
src/sst/jucegui/components/KnobPainter.hxx
src/sst/jucegui/components/VSlider.cpp

1. component-adapters exist for at least a simple discrete case
2. Make the componet take Continuous or ContinuousModulatable so not every client needs to drag around the modulation api.

Start of a collection of cleanups

---

include/sst/jucegui/accessibility/FocusDebugger.h
include/sst/jucegui/accessibility/Ignored.h
include/sst/jucegui/components/CallbackButtonComponent.h
include/sst/jucegui/components/ComponentBase.h
include/sst/jucegui/components/DiscreteParamEditor.h
include/sst/jucegui/components/Label.h
include/sst/jucegui/components/NamedPanel.h
include/sst/jucegui/components/WindowPanel.h
src/sst/jucegui/components/ContinuousParamEditor.cpp
src/sst/jucegui/components/NamedPanel.cpp

This has the necessary changes so Conduit elements are at least labeled properly and light up, albeit always as groups, in the accessibility view. it also starts adding some of the utilities we need to get surge level accessibility here.

Accessibility Support: Step 1

---

src/sst/jucegui/components/ComponentBase.cpp

If an object was hovered / idle timered while deleted it would crash. This would casue, for instance, group add errors in SCXT.
Clean up by safeul removing self in destructor of interface

WithIdleTimer destructor cleanup

---

include/sst/jucegui/components/NamedPanel.h
include/sst/jucegui/components/WindowPanel.h
include/sst/jucegui/style/CustomizationTools.h
include/sst/jucegui/style/StyleAndSettingsConsumer.h
include/sst/jucegui/style/StyleSheet.h
src/sst/jucegui/components/KnobPainter.hxx
src/sst/jucegui/components/NamedPanel.cpp
src/sst/jucegui/components/VSlider.cpp
src/sst/jucegui/style/StyleSheet.cpp

- Add the CustomizationTools to make custom styles easier
- Add the position debugger to the named panel
- More work on figma ui matching, including optional transparent knobs
- Styleshee Mechanics Cleanups
- Plenty of other little tweaks here and there

JuceGUI changes towards the SCXT Figma Themes

---

include/sst/jucegui/components/LabeledItem.h

holds a T and a Label. Obioulsy. But useful for SCXT idioms which will become jucegui idioms for layout in the future

A Labeled<T> class

---

include/sst/jucegui/components/DiscreteParamMenuBuilder.h
src/sst/jucegui/components/DiscreteParamMenuBuilder.cpp
src/sst/jucegui/components/JogUpDownButton.cpp

The PMB give syou menu order traversals in group list mode. Basically lets you do the surge filter ui properly.

ParamMenuBulder can do menu order jog. JogMenu uses it

---

include/sst/jucegui/components/ButtonPainter.h
include/sst/jucegui/components/GlyphPainter.h
src/sst/jucegui/components/GlyphPainter.cpp
src/sst/jucegui/components/HSlider.cpp
src/sst/jucegui/components/JogUpDownButton.cpp
src/sst/jucegui/components/MultiSwitch.cpp
src/sst/jucegui/components/ToggleButton.cpp

The toggle button uses a non-filled pwoer button for off state basically

Add a power-off button and clang-format

---

include/sst/jucegui/components/GlyphButton.h
src/sst/jucegui/components/GlyphButton.cpp

GlyphButton can have a pair of glyphs

---

include/sst/jucegui/components/BaseStyles.h
include/sst/jucegui/components/ButtonPainter.h
include/sst/jucegui/components/ToggleButton.h
include/sst/jucegui/style/StyleAndSettingsConsumer.h
src/sst/jucegui/components/ToggleButton.cpp

Filled toggle buttons look like this now:

toggle button filled style implementation

---

include/sst/jucegui/components/DraggableTextEditableValue.h
src/sst/jucegui/components/DraggableTextEditableValue.cpp
src/sst/jucegui/components/MultiSwitch.cpp
src/sst/jucegui/style/StyleSheet.cpp

Changed:
- HSliderFilled
- DraggableTextEditableValue
- MultiSwitch (fixed the one that is not Modulation)
Looking like this now in SC:

Component Colours Improvement

---

include/sst/jucegui/components/HSliderFilled.h
src/sst/jucegui/components/HSliderFilled.cpp

verticalReduction is a settable member so you can distinguish active zone from paint zone, making up for the lack of a handle hit zone while still keeping a gutter-only look

HSliderFilled can have skinny paint zone and broad hit zone

---

examples/component-demo/SSTJuceGuiDemo.cpp
examples/component-demo/ZoomContainerDemo.h
include/sst/jucegui/components/ZoomContainer.h

This commit adds components::ZoomContainer which is an object which collaborates with a component that can internalize its draws based on scale and starting position. Defacto this will let us make the shortcircuit sample zoom way faster because we can just know start points and end points.
The mouse gestures are, I think right. For a mac trackpad they are glorious. But we will need to adjust them for win/lin mice I'm sure.

A zoom container which isn't a viewport

---

CMakeLists.txt
examples/component-demo/ListViewDemo.h
examples/component-demo/SSTJuceGuiDemo.cpp
include/sst/jucegui/components/ListView.h
src/sst/jucegui/components/ListView.cpp

A list view which is more component based etc... and delegates more to the indiidual components. Still a WIP.

A lighter weight list view

---

CMakeLists.txt

- updated juce 7 -> juce 8.0.4 since I'm running osx 15
- new flag `SST_JUCEGUI_SKIP_AUDIO` which can be override downstream to add or to skip the audio flags. 
baconpaul said in discord: 
```
It always zeroes out CURL and WEB_BROWSER. Those have to stay defined
It has an option called "SST_JUCEGUI_SKIP_AUDIO" which defaults to true
if it is true you add those definitions for jack -> directsound
surge sets it to false in lib.cmake before including
```
I think he meant
```It has an option called "SST_JUCEGUI_SKIP_AUDIO" which defaults to true
if it is **FALSE** you add those definitions for jack -> directsound
```
cus  - y'know -
"skip audio" mean "don't add audio flags" 
NOT "skip audio" means "add flags"
horray for confusing double negatives
but opening it up to discussion.

Conditional audio flags

---

CMakeLists.txt
include/sst/jucegui/components/DiscreteParamEditor.h
include/sst/jucegui/components/DiscreteParamMenuBuilder.h
include/sst/jucegui/components/JogUpDownButton.h
include/sst/jucegui/components/ToggleButton.h
src/sst/jucegui/components/ContinuousParamEditor.cpp
src/sst/jucegui/components/DiscreteParamEditor.cpp
src/sst/jucegui/components/DiscreteParamMenuBuilder.cpp
src/sst/jucegui/components/JogUpDownButton.cpp
src/sst/jucegui/components/MultiSwitch.cpp
src/sst/jucegui/components/ToggleButton.cpp

Implement some rudimentary accesibility for discrete params. This means
1. Most discrete params now get a menu on RMB
2. Repaints, notifies, etc... are all fixed up
3. There's a discrete AH for the components which defaults to slider but which can be overridden for toggle
4. There's a keyboard handler
Immediate improvement in six sines accesibility (and short circuit too once I merge it) but still some work to go

Accesibility: Discrete Params

---

include/sst/jucegui/accessibility/FocusDebugger.h
include/sst/jucegui/accessibility/KeyboardTraverser.h
include/sst/jucegui/components/ContinuousParamEditor.h
include/sst/jucegui/components/DiscreteParamEditor.h
include/sst/jucegui/components/WindowPanel.h
src/sst/jucegui/components/JogUpDownButton.cpp

Add an explicit keyboard traversal support which assumes all editable components are labeled or labelable and so allows tab order to be specified explicitly as subordinate to parent components, which have a group orering index.

Keyboard traversal support

---

CMakeLists.txt
include/sst/jucegui/accessibility/KeyboardTraverser.h
include/sst/jucegui/component-adapters/ComponentTags.h
src/sst/jucegui/component-adapters/ComponentTags.cpp

Add compoennt tags api. Add ones for clap param, traversal id, and full traversal id. Use these in KeyboardAccesibilityThingy

Component Tags in JuceGui

---

include/sst/jucegui/components/MultiSwitch.h
src/sst/jucegui/components/MultiSwitch.cpp

allowing robust menus and spoken words with a more compact visual ui.

Allow abbreviated displays on multiswithes

---

include/sst/jucegui/components/ComponentBase.h
include/sst/jucegui/components/DiscreteParamEditor.h
src/sst/jucegui/components/ComponentBase.cpp
src/sst/jucegui/components/ContinuousParamEditor.cpp

A variaety of tooltip timer fixes which led to stuck tooltips and no tooltips on mouse wheel. Basically an API which lets you set up six sines and short circuit properly now

A variety of tooltip timer fixes

---

include/sst/jucegui/util/VisibilityParentWatcher.h

which forces visibilityChanged calls for you *or your parent* visibility changing, optionally.

Add a VisibilityParentWatcher utility

---

include/sst/jucegui/components/ListView.h
src/sst/jucegui/components/ListView.cpp

so we can be consistent on keymod activities rather than figuring it out in the clients

Add a list view multi select by key mod

---

include/sst/jucegui/components/DraggableTextEditableValue.h
include/sst/jucegui/data/Continuous.h
src/sst/jucegui/components/DraggableTextEditableValue.cpp

The units in tight text edit drags were ... the string so add an api so e can skip them, which defaults to the regular string if a continuous doesnt' implement it

Add 'no-unit' api to continuous; use it in draggable text edit

---

CMakeLists.txt
include/sst/jucegui/components/CompactPlot.h
src/sst/jucegui/components/CompactPlot.cpp
src/sst/jucegui/style/StyleSheet.cpp

which is a virtual class that can calculate a curve on (0,1) and an axis bound and does an OK plot. Currently a bit early but works for the ShortCircuit LFO at least.

Add a CompactPlot widget

---

include/sst/jucegui/components/CompactPlot.h
include/sst/jucegui/data/CompactPlotSource.h
include/sst/jucegui/data/Continuous.h
include/sst/jucegui/data/Discrete.h
include/sst/jucegui/data/WithDataListener.h
src/sst/jucegui/components/CompactPlot.cpp

1. Source separate from Renderer, like the rest of the kit
2. Make the has data listener lifecycle loop thingy a base class to avoid a third copy; normalize continuous and discrete cases to use it also

More CompactPlot factoring

---

include/sst/jucegui/components/GlyphPainter.h
include/sst/jucegui/components/JogUpDownButton.h
include/sst/jucegui/components/NamedPanel.h
src/sst/jucegui/components/GlyphPainter.cpp
src/sst/jucegui/components/JogUpDownButton.cpp
src/sst/jucegui/components/NamedPanel.cpp
src/sst/jucegui/components/ToolTip.cpp

- Named Panel can do an inter-border title
- UpDown jog can position arrow LR or AllRight
- Add Hamburger and Dice glyphs to GlyphPainter

Options used in Elfin

---

include/sst/jucegui/screens/ScreenHolder.h
src/sst/jucegui/components/ListView.cpp

basically the onCB can still use the imte so yield the UI thread when visibility change detected before delete

Fix an order-of-deletion problem which made a windows crash
