- CMakeLists.txt
- README.md
- examples/CoupledControls.h
- examples/ExampleUtils.h
- examples/HSliderDemo.h
- examples/KnobDemo.h
- examples/MixerPrototype.h
- examples/MultiSwitchDemo.h
- examples/NamedPanelDemo.h
- examples/SSTJuceGuiDemo.cpp
- examples/ToggleDemo.h
- examples/VSliderDemo.h
- include/sst/jucegui/components/MultiSwitch.h
- include/sst/jucegui/data/Continuous.h
- include/sst/jucegui/data/Discrete.h
- src/sst/jucegui/components/MultiSwitch.cpp
- src/sst/jucegui/style/StyleSheet.cpp
- First of all tighten up the example harness a bit
- Add a Multiswitch and a discrete with named list
- Add basic render and mouse events
> MultiSwitch Work

- CMakeLists.txt
- README.md
- examples/SSTJuceGuiDemo.cpp
- examples/TreeTableFileSystem.h
- include/sst/jucegui/components/TabularizedTreeViewer.h
- include/sst/jucegui/data/TreeTable.h
- src/sst/jucegui/components/MultiSwitch.cpp
- src/sst/jucegui/components/TabularizedTreeViewer.cpp
- src/sst/jucegui/data/TreeTable.cpp
- src/sst/jucegui/style/StyleSheet.cpp
Enough of a tree widget that I want at least a moment checkpoint
> TreeTable Widget; MultiSwitch tweaks

- CMakeLists.txt
- README.md
- examples/DraggableTextDemo.h
- examples/SSTJuceGuiDemo.cpp
- include/sst/jucegui/components/DraggableTextEditableValue.h
- include/sst/jucegui/data/Continuous.h
- src/sst/jucegui/components/DraggableTextEditableValue.cpp
- src/sst/jucegui/style/StyleSheet.cpp
It more or less works but doesn't have a drak skin style. I
realized I want to change the style implementation a bit so want
to do that first but get this checkpointed out of the way.
> Start of a Draggable Typein

- examples/SSTJuceGuiDemo.cpp
- include/sst/jucegui/components/BaseStyles.h
- include/sst/jucegui/components/ContinuousParamEditor.h
- include/sst/jucegui/components/DraggableTextEditableValue.h
- include/sst/jucegui/components/HSlider.h
- include/sst/jucegui/components/Knob.h
- include/sst/jucegui/components/Label.h
- include/sst/jucegui/components/MultiSwitch.h
- include/sst/jucegui/components/NamedPanel.h
- include/sst/jucegui/components/TabularizedTreeViewer.h
- include/sst/jucegui/components/ToggleButton.h
- include/sst/jucegui/components/VSlider.h
- include/sst/jucegui/components/WindowPanel.h
- include/sst/jucegui/style/StyleAndSettingsConsumer.h
- include/sst/jucegui/style/StyleSheet.h
- src/sst/jucegui/components/DraggableTextEditableValue.cpp
- src/sst/jucegui/components/HSlider.cpp
- src/sst/jucegui/components/Knob.cpp
- src/sst/jucegui/components/NamedPanel.cpp
- src/sst/jucegui/components/TabularizedTreeViewer.cpp
- src/sst/jucegui/style/StyleAndSettingsComsumer.cpp
- src/sst/jucegui/style/StyleSheet.cpp
1. The hierarchy is way cleaner and in memory
2. The nodes are constexpr but the strucvture is post-static runtime
for faster dll load and more flex
3. Reasonable hierachy of styles
> Rework StyleSheet some

- README.md
- examples/CustomStyleDemo.h
- examples/ExampleUtils.h
- examples/SSTJuceGuiDemo.cpp
- include/sst/jucegui/style/StyleSheet.h
- src/sst/jucegui/style/StyleSheet.cpp
Mostly convince myself that a component can have a custom
superclass, which this demonstrates it can, and that the
resolution and creation works. But along the way add a setColor
and change parent relationship resolution in isValid
> Custom Style Demo

- CMakeLists.txt
- README.md
- include/sst/jucegui/components/BaseStyles.h
- include/sst/jucegui/components/HSlider.h
- include/sst/jucegui/components/MultiSwitch.h
- include/sst/jucegui/components/NamedPanel.h
- include/sst/jucegui/components/WindowPanel.h
- include/sst/jucegui/data/Labeled.h
- src/sst/jucegui/components/ContinuousParamEditor.cpp
- src/sst/jucegui/components/HSlider.cpp
- src/sst/jucegui/components/MultiSwitch.cpp
- src/sst/jucegui/components/NamedPanel.cpp
- src/sst/jucegui/components/ToggleButton.cpp
- src/sst/jucegui/components/VSlider.cpp
- src/sst/jucegui/style/StyleSheet.cpp
This is a set of changes which I made as I started using it
in an actual app. Incremental push
> First changes to get working in shortcircuit

- src/sst/jucegui/components/VSlider.cpp
ToDo: All the other widgets. Sigh.
> VSlider responsd to enabled with at least something

- include/sst/jucegui/components/BaseStyles.h
- include/sst/jucegui/style/StyleSheet.h
- src/sst/jucegui/components/NamedPanel.cpp
- src/sst/jucegui/components/VSlider.cpp
- src/sst/jucegui/style/StyleSheet.cpp
- Labels to 12pt in default
- Add a handle border color
- Tighten up vslider drawing a bit
- make it so you can sub the font in one go after setup
> Few more SCXT Changes

- include/sst/jucegui/components/NamedPanel.h
- src/sst/jucegui/components/NamedPanel.cpp
- src/sst/jucegui/style/StyleSheet.cpp
And some style tweaks to go along
> Named Panel gets Tabs, Hamburgers

- CMakeLists.txt
- include/sst/jucegui/components/CallbackButtonComponent.h
- include/sst/jucegui/components/GlyphButton.h
- include/sst/jucegui/components/GlyphPainter.h
- src/sst/jucegui/components/GlyphButton.cpp
- src/sst/jucegui/components/GlyphPainter.cpp
- src/sst/jucegui/style/StyleSheet.cpp
Also factor GlyphPainter so it has both a component and a static paint mode.
> GlyphButton class which is a button painting a Glyph

- include/sst/jucegui/components/Label.h
> Label gets Justification property

- CMakeLists.txt
- include/sst/jucegui/components/ComponentBase.h
- include/sst/jucegui/components/ContinuousParamEditor.h
- src/sst/jucegui/components/ComponentBase.cpp
Which allows SC to pop a tooltip over an idled knob for instance
> Add an on-mouse-idle timer and callback

- CMakeLists.txt
- include/sst/jucegui/components/NamedPanelDivider.h
- src/sst/jucegui/components/NamedPanelDivider.cpp
- src/sst/jucegui/style/StyleSheet.cpp
the two rounded rects from the wireframe basically
> Add NamedPanelDivider

- include/sst/jucegui/components/VUMeter.h
- src/sst/jucegui/style/StyleSheet.cpp
Good enough for people to look at in conduit, at least. Vertical only still
> An improved VUMeter

- include/sst/jucegui/layouts/LabeledGrid.h
- specify item size
- fill across blank label
- etc
> Momre tweaks for LabeledGrid layout class

- include/sst/jucegui/layouts/LabeledGrid.h
- src/sst/jucegui/components/MultiSwitch.cpp
Labeled Grid gets colspan, col gap API changed.
Multiswitch in horizontal mode had an off-by-one error
> Labeled Grid Colspan etc... Multiswitch Bug Fix

- src/sst/jucegui/components/KnobPainter.hxx
> Warning Fix

- include/sst/jucegui/components/ButtonPainter.h
- src/sst/jucegui/components/GlyphButton.cpp
- src/sst/jucegui/components/TextPushButton.cpp
- src/sst/jucegui/components/ToggleButton.cpp
- src/sst/jucegui/style/StyleSheet.cpp
Mostly some small changes to the buttons but also some other refactors.
> Upgrades for SC port

- CMakeLists.txt
- include/sst/jucegui/components/ToolTip.h
- src/sst/jucegui/components/ToolTip.cpp
- src/sst/jucegui/style/StyleSheet.cpp
based on the one from shortcircuit
> Move a ToolTip component here

- include/sst/jucegui/components/DiscreteParamEditor.h
- include/sst/jucegui/data/Discrete.h
my fix of the shutdown path skipped the discrete case improperly
> Fix a shutdown problem in Discrete param editrs

- include/sst/jucegui/accessibility/FocusDebugger.h
- include/sst/jucegui/data/Continuous.h
- A missing const
- FocusDebugger is a has-a not is-a relationship. Duh!
> Accessibility three: Changes from intro to SCXT

- include/sst/jucegui/components/BaseStyles.h
- include/sst/jucegui/components/NamedPanel.h
- src/sst/jucegui/components/NamedPanel.cpp
- src/sst/jucegui/style/StyleSheet.cpp
which got lost in the stylesheet shuffle
> Restore Named Panel Select Behavior

- include/sst/jucegui/components/NamedPanel.h
- src/sst/jucegui/components/ToggleButtonRadioGroup.cpp
- src/sst/jucegui/style/StyleAndSettingsConsumer.cpp
Cleans up some sanitizer goobits left over in SC, but also just good practice
> Only resize or repaint showing objects on style changes

- include/sst/jucegui/components/ToggleButton.h
- src/sst/jucegui/components/JogUpDownButton.cpp
- src/sst/jucegui/components/ToggleButton.cpp
- in LABELED_BY_DATA the toggle button just swaps between two strings ratther than use the label and on off
- UpDown hover colors arrows as you mouse them directly not if you mouse anywhere
> ToggleButton gets LABEL_BY_DATA; JogUpDown gets proper hovers

- examples/component-demo/KnobDemo.h
- src/sst/jucegui/components/KnobPainter.hxx
especially small knobs, but also just smaller value rings
> Fix some of the knob drawing bugs which bugged me

- src/sst/jucegui/components/ToolTip.cpp
Mostly so the SCXT modulation looks better
> Sligntly improve the tooltip layout and appearance

- include/sst/jucegui/components/ScrollBar.h
- include/sst/jucegui/components/Viewport.h
- src/sst/jucegui/style/StyleSheet.cpp
Just dropin sst::jucegui::components::Viewport for juce::Viewport and everythign works
> Add stylesheet aware viewport and scrollbar classes

- CMakeLists.txt
- src/sst/jucegui/components/ContinuousParamEditor.cpp
since it was way too high. This may be way too low but at least it puts a factor in we can noodle with.
Addresses https://github.com/surge-synthesizer/shortcircuit-xt/issues/786
> Scale the win/lin mouse down some

- include/sst/jucegui/components/NamedPanel.h
- include/sst/jucegui/components/TabbedComponent.h
- include/sst/jucegui/style/StyleAndSettingsConsumer.h
- src/sst/jucegui/components/NamedPanel.cpp
- src/sst/jucegui/style/StyleAndSettingsConsumer.cpp
- src/sst/jucegui/style/StyleSheet.cpp
- Start of Tabbed Panel but its not even close to styled. Merging so I can get melatonin in folks hands
- As a result drop the positio ndebugger
- and add a method to just call onStyleChanged down the tree
> Tabbed Panel Component starts; Drop Position Debugger; Notify Style

- include/sst/jucegui/components/GlyphPainter.h
- include/sst/jucegui/components/NamedPanel.h
- src/sst/jucegui/components/GlyphPainter.cpp
- src/sst/jucegui/components/NamedPanel.cpp
- src/sst/jucegui/components/ToggleButton.cpp
1. The GlyphPainter gets a 3 key keyboard glyph which looks OK
2. The NamedPanel gets additionalHamberugerComponents which stack up next to the hamburger menu control if you want them.
> Keyboard Glyph; Extra Hamburgers in Named Panels

- src/sst/jucegui/components/DiscreteParamMenuBuilder.cpp
We didn't wrap properly at jog ends in the discrete menu builder. Now we do!
> Jog fix for wrapping

- include/sst/jucegui/data/Discrete.h
- src/sst/jucegui/components/JogUpDownButton.cpp
So you can either wrap or not.
Defailt remains you do
Also change the JUDB to respond
> Add discrete jog wrap behavior toggle

- include/sst/jucegui/components/NamedPanel.h
- src/sst/jucegui/components/NamedPanel.cpp
rather than just mukcing with internals
> NamedPanel has a public method to change tab selection

- include/sst/jucegui/components/ContinuousParamEditor.h
- include/sst/jucegui/components/TypeInOverlay.h
- src/sst/jucegui/components/ContinuousParamEditor.cpp
- src/sst/jucegui/style/StyleSheet.cpp
Shift-Dbl-Click or Shift-Return launches a typein.
WIP - still more to do. But functional.
> Typeins for Continuous Items

- include/sst/jucegui/data/Continuous.h
- src/sst/jucegui/components/ContinuousParamEditor.cpp
So we can do quantized drags via the interface
> Add setValueFromGUIQuantized and use it in the ContEditor

- include/sst/jucegui/components/RuledLabel.h
- include/sst/jucegui/layouts/ExplicitLayout.h
- src/sst/jucegui/style/StyleSheet.cpp
All part of starting to restructure the bus screens in SCXT but useful for more than just that.
> Add initial explicit layout class. Add ruled label

- include/sst/jucegui/component-adapters/DiscreteToReference.h
Mostly so I can do labeled multisiwthces with it
> DiscreteToValueReference gets a user defined tostring function

- include/sst/jucegui/components/VUMeter.h
- src/sst/jucegui/components/HSliderFilled.cpp
- src/sst/jucegui/components/VSlider.cpp
> Filled H and V Sliders are square not rounded rects

- src/sst/jucegui/components/KnobPainter.hxx
> Flatten the knobs in knob body mode some

- .github/workflows/build-pr.yml
- CMakeLists.txt
- examples/component-demo/CMakeLists.txt
- examples/scxt-wireframes/CMakeLists.txt
SST Jucegui has a unity build and no longer has
jucegui as a public dependency (but strips some
options and so on)
> Towards a unity build

- CMakeLists.txt
> Move Unity to a generator expression style

- include/sst/jucegui/components/NamedPanel.h
- src/sst/jucegui/components/NamedPanel.cpp
- src/sst/jucegui/style/StyleSheet.cpp
Cursor over the text area if you set it. Accent is a color you can toggle on or off.
> Named Panel gets cursor and accent mode

- include/sst/jucegui/components/ToolTip.h
- src/sst/jucegui/components/ToolTip.cpp
> Tooltip gets a row data structure

- include/sst/jucegui/components/ZoomContainer.h
Also flip sign on wheel zoom gestures
> ZoomContainer Translate is porporational to size

- include/sst/jucegui/components/RuledLabel.h
> Wow - ruled label was here!

- include/sst/jucegui/components/CallbackButtonComponent.h
Label, Title, Handler and press enter to fire
> CallbackButtonBase gets accesibility

- src/sst/jucegui/components/JogUpDownButton.cpp
- src/sst/jucegui/components/MultiSwitch.cpp
- jogupdown didnt
- multiswitch did, but then did again!
> Fix some begin/end edit shenanigans

- CMakeLists.txt
- include/sst/jucegui/components/GlyphPainter.h
- res/glyphs/minus.svg
- src/sst/jucegui/components/GlyphPainter.cpp
> We had a PLUS glyph but not a MINUS glyph

- include/sst/jucegui/components/BaseStyles.h
- include/sst/jucegui/style/JUCELookAndFeelAdapter.h
- src/sst/jucegui/style/StyleSheet.cpp
1. Add a look and feel manager which does the shared pointer rigamarole.
2. Once thats there, you can add PopupMenu colors to the style sheet, so do so here.
> Add a central point managing LnF; Move popup to stylesheet

- src/sst/jucegui/components/ContinuousParamEditor.cpp
which apparently people still use! Huh.
> Deal with macos unidrectional wheel pointer devices

- src/sst/jucegui/components/TextEditor.cpp
skp some things if there's no text when we change styles which helps SC startup a bunch
> Text Editor Optimizations

- include/sst/jucegui/components/ListView.h
- src/sst/jucegui/components/ListView.cpp
so we can reset external selection for instance
> Add reassign method to ListView

- include/sst/jucegui/components/ComponentBase.h
- include/sst/jucegui/components/ToolTip.h
- src/sst/jucegui/components/ToolTip.cpp
1. User controllable delay until idle for the idle hover timer
2. Title alighnment in the tooltip class
> Tooltip Changes

- include/sst/jucegui/components/Label.h
- include/sst/jucegui/screens/AlertOrPrompt.h
- include/sst/jucegui/screens/ModalBase.h
- include/sst/jucegui/screens/ScreenHolder.h
- src/sst/jucegui/style/StyleSheet.cpp
1. Introduce a concept of 'screens' - larger compound elements
2. Add a ModalBase for modal screens and a ScreenHolder which you can subclass to have utilities which allow you to do modal overlays
3. Add an AlertOrPrompt which has an error or an ok/cancel type thing and is extensible for more.
4. Make Label capable of multiline
> A 'Screen' Abstraction and an Alert/OKCancel implementation

- include/sst/jucegui/components/CallbackButtonComponent.h
If you add a jog callback (dir) to the CallbackButtonCompponent deriverd classes, both mouse wheens and arrow jogs can call through appropriately, for your button to implement as it sees fit.
> CallbackButtonComponent gets optional jog handler
